[package]
name = "bevy-pointerlockchange-hook"
version = "0.14.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = ["bevy_winit"] }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3", features = ["Window", "Document", "Element"] }
